# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0002_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Views',
            new_name='views',
        ),
    ]
