# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0005_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleDotCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
