# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0006_exampledotcom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleDotCom',
        ),
    ]
