# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0008_newsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='url',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
