# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0009_auto_20170819_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
