# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0013_auto_20170819_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('data', models.TextField(blank=True, verbose_name='configuration data')),
            ],
            options={
                'ordering': ['ordering', 'name'],
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='timestamp')),
                ('object_url', models.URLField(unique=True, verbose_name='object URL')),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='author')),
                ('body', models.TextField(blank=True, help_text='Content of the story. May contain HTML.', verbose_name='body')),
                ('image_url', models.CharField(blank=True, max_length=1000, verbose_name='image URL')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='QA_blog.Source', verbose_name='source')),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.AddField(
            model_name='extradata',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA_blog.Story'),
        ),
        migrations.AlterUniqueTogether(
            name='extradata',
            unique_together=set([('story', 'key')]),
        ),
    ]
