# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0014_auto_20170819_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='extradata',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='extradata',
            name='story',
        ),
        migrations.RemoveField(
            model_name='story',
            name='source',
        ),
        migrations.DeleteModel(
            name='ExtraData',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
