# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0015_auto_20170819_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='author_name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
