# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0016_auto_20170820_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
