# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0020_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
