# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0023_auto_20170828_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedvideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
