# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0025_embedvideo_videotext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Embedvideo',
        ),
    ]
