# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0028_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
