# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0030_auto_20170917_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='guide_price',
            new_name='price',
        ),
    ]
