# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0032_auto_20170917_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='guide_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
