# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0033_video_guide_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='guide_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='guide_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='guide_price',
            new_name='price',
        ),
    ]
