# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0036_auto_20170917_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='guide_image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='guide_name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='price',
            new_name='guide_price',
        ),
    ]
