# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0038_highestrated_topfivegames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighestRated',
        ),
        migrations.DeleteModel(
            name='TopFiveGames',
        ),
    ]
