# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0040_auto_20170929_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Awful'), (0, 'Poor'), (0, 'Average'), (0, 'Good'), (1, 'Outstanding')]),
        ),
    ]
