# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0041_auto_20170929_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Awful'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Outstanding')]),
        ),
    ]
