# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_blog', '0042_auto_20170929_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='game_description',
            new_name='guide_description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='game_image',
            new_name='guide_image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='game_name',
            new_name='guide_name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='game_price',
            new_name='guide_price',
        ),
    ]
